version: '3.8'
services:
  app:
    build:
      args:
        user: marin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: trail-app-image
    container_name: trail-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: trail-app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: postgres:13
    container_name: trail-app-db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:


